// src/pages/TermsOfService.jsx
import React from 'react';
import { Link } from 'react-router-dom';

const Section = ({ title, children }) => (
  <div className="mb-10">
    <h2 className="text-lg font-black text-white mb-4 pb-2 border-b border-white/5">{title}</h2>
    <div className="space-y-3 text-gray-400 text-sm leading-relaxed">{children}</div>
  </div>
);

const TermsOfService = () => {
  return (
    <div className="min-h-screen bg-[#0f172a] text-white font-sans">
      {/* Header */}
      <header className="border-b border-white/5 bg-[#0f172a]/80 backdrop-blur-xl sticky top-0 z-50">
        <div className="max-w-4xl mx-auto px-6 h-14 flex items-center justify-between">
          <Link to="/" className="flex items-center gap-2 font-black tracking-tighter text-lg">
            <span className="bg-gradient-to-r from-indigo-500 to-purple-600 w-7 h-7 rounded-lg flex items-center justify-center text-[10px]">AI</span>
            AILETTER
          </Link>
          <Link to="/" className="text-xs text-gray-400 hover:text-white transition-colors">← Back to Home</Link>
        </div>
      </header>

      {/* Content */}
      <main className="max-w-4xl mx-auto px-6 py-16">
        <div className="mb-12">
          <h1 className="text-4xl font-black mb-3">Terms of Service</h1>
          <p className="text-gray-500 text-sm">Last updated: February 2025</p>
        </div>

        <Section title="1. Acceptance of Terms">
          <p>By accessing or using AIletter ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our Service.</p>
          <p>These terms apply to all users, including visitors, registered users, and Pro subscribers.</p>
        </Section>

        <Section title="2. Description of Service">
          <p>AIletter is an AI-powered cover letter generation tool. The Service allows users to upload their CV, input job descriptions, and generate personalized cover letters using artificial intelligence.</p>
          <p>We offer a Free tier (5 generations/month) and a Pro subscription with unlimited generations and additional features.</p>
        </Section>

        <Section title="3. User Accounts">
          <p>You must create an account to use AIletter. You are responsible for maintaining the security of your account credentials and for all activities that occur under your account.</p>
          <p>You must provide accurate and complete information when creating your account. You may not use another person's account without permission.</p>
          <p>We reserve the right to terminate accounts that violate these Terms or that have been inactive for extended periods.</p>
        </Section>

        <Section title="4. Acceptable Use">
          <p>You agree not to use AIletter to:</p>
          <ul className="list-disc pl-5 space-y-2 mt-2">
            <li>Generate content that is fraudulent, misleading, or deceptive</li>
            <li>Submit false information to employers or job platforms</li>
            <li>Violate any applicable laws or regulations</li>
            <li>Attempt to reverse-engineer or extract our AI models</li>
            <li>Use automated means to access the Service beyond normal use</li>
            <li>Share your account with multiple users (Pro accounts are individual)</li>
          </ul>
        </Section>

        <Section title="5. Intellectual Property">
          <p>The cover letters generated by AIletter are provided for your personal use. You own the content of letters you generate, but AIletter retains rights to the underlying technology, models, and platform.</p>
          <p>AIletter's branding, design, and software are protected by copyright and other intellectual property laws. You may not reproduce or redistribute our platform without permission.</p>
        </Section>

        <Section title="6. Payments and Subscriptions">
          <p>Pro subscriptions are billed monthly or annually. Payments are processed securely through Stripe. By subscribing, you authorize recurring charges to your payment method.</p>
          <p>You may cancel your subscription at any time. Cancellation takes effect at the end of the current billing period. We do not offer refunds for partial billing periods.</p>
          <p>We reserve the right to change pricing with 30 days' notice. Continued use after price changes constitutes acceptance of new pricing.</p>
        </Section>

        <Section title="7. Privacy and Data">
          <p>Your use of AIletter is also governed by our <Link to="/privacy" className="text-indigo-400 hover:text-indigo-300 transition-colors">Privacy Policy</Link>, which is incorporated into these Terms by reference.</p>
          <p>CV data you upload is processed to generate cover letters and is not stored permanently on our servers beyond the active session unless you explicitly save it.</p>
        </Section>

        <Section title="8. Disclaimer of Warranties">
          <p>AIletter is provided "as is" without warranties of any kind. We do not guarantee that generated letters will result in job interviews or employment. The quality of output depends on the quality of input provided.</p>
          <p>We are not responsible for any decisions made by employers based on letters generated through our Service.</p>
        </Section>

        <Section title="9. Limitation of Liability">
          <p>To the maximum extent permitted by law, AIletter shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service.</p>
          <p>Our total liability to you for any claims arising from these Terms shall not exceed the amount you paid us in the 3 months preceding the claim.</p>
        </Section>

        <Section title="10. Changes to Terms">
          <p>We may update these Terms at any time. We will notify registered users of significant changes via email or in-app notification. Continued use of the Service after changes constitutes acceptance.</p>
        </Section>

        <Section title="11. Contact">
          <p>For questions about these Terms, contact us at: <a href="mailto:legal@ailetter.app" className="text-indigo-400 hover:text-indigo-300 transition-colors">legal@ailetter.app</a></p>
        </Section>
      </main>

      {/* Footer */}
      <footer className="border-t border-white/5 py-8 px-6 text-center text-xs text-gray-600">
        <div className="flex justify-center gap-6 mb-3">
          <Link to="/terms" className="hover:text-gray-400 transition-colors text-indigo-400">Terms of Service</Link>
          <Link to="/privacy" className="hover:text-gray-400 transition-colors">Privacy Policy</Link>
          <Link to="/" className="hover:text-gray-400 transition-colors">Home</Link>
        </div>
        © 2025 AIletter. All rights reserved.
      </footer>
    </div>
  );
};

export default TermsOfService;