const MODELS = [
  { id: "gemini-2.5-flash",      temp: 0.7 },
  { id: "gemini-2.5-flash-lite", temp: 0.6 },
  { id: "gemini-2.5-pro",        temp: 0.7 },
];

const sleep = ms => new Promise(r => setTimeout(r, ms));

async function callGemini({ modelId, temperature, maxOutputTokens, contents, responseMimeType }) {
  const response = await fetch("/api/generate", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ modelId, temperature, maxOutputTokens, contents, responseMimeType }),
  });

  const data = await response.json();

  if (!response.ok) {
    const error = new Error(data.error?.message || "Gemini API error");
    error.status = response.status;
    throw error;
  }

  return data.candidates?.[0]?.content?.parts?.[0]?.text ?? "";
}

async function tryModel(modelFn) {
  let modelIndex = 0;
  while (modelIndex < MODELS.length) {
    const current = MODELS[modelIndex];
    try {
      console.log(`Using model: ${current.id}`);
      return await modelFn(current.id, current.temp);
    } catch (error) {
      console.warn(`${current.id} failed:`, error);
      const isCritical = error.status === 429 || error.status === 404 || error.status === 503;
      if (isCritical) {
        modelIndex++;
        if (modelIndex < MODELS.length) {
          await sleep(1000);
          continue;
        }
      }
      throw error;
    }
  }
  throw new Error("AI is busy. Please try again.");
}

export const generateLetter = async (userProfile, jobDescription, cvFilePart, settings) => {
  const { language, tone, length } = settings;

  const wordLimit =
    length === "Short"    ? "250-300" :
    length === "Detailed" ? "380-420" :
                            "320-370";

  const lang = language === "Auto" ? "the same language as the job description" : language;

  const candidateProfile = `
- Full Name: ${userProfile.fullName || "Not provided"}
- Current Role: ${userProfile.profession || "Not provided"}
- Location: ${userProfile.location || "Not specified"}
- Key Skills: ${Array.isArray(userProfile.skills) ? userProfile.skills.join(", ") : (userProfile.skills || "Not provided")}
- Recent Experience: ${
    Array.isArray(userProfile.experience)
      ? userProfile.experience.map(e =>
          `${e.title} at ${e.company} (${e.duration}): ${(e.achievements || []).join("; ")}`
        ).join(" | ")
      : (userProfile.experience || "Not provided")
  }
- Education: ${userProfile.education || "Not specified"}
- Languages: ${Array.isArray(userProfile.languages) ? userProfile.languages.join(", ") : (userProfile.languages || "Not specified")}
- Certifications: ${Array.isArray(userProfile.certifications) ? userProfile.certifications.join(", ") : (userProfile.certifications || "None")}
- Email: ${userProfile.email || "Not provided"}
- LinkedIn: ${userProfile.linkedin || "Not provided"}
  `.trim();

  const promptText = `
You are a senior career coach who writes cover letters that sound like they were written by a thoughtful, confident human — not generated by AI.

TASK:
Write a cover letter in ${lang} for the candidate below. The letter must feel personal, specific, and alive — like a real person speaking directly to the hiring manager.

══════════════════════════════════════════
GENDER & GRAMMAR — CRITICAL:
══════════════════════════════════════════
- Infer the candidate's gender from their full name.
- Apply correct grammatical gender agreement throughout the ENTIRE letter in ANY language with grammatical gender (Ukrainian, Italian, German, French, Spanish, etc.).
- Examples:
  Ukrainian female: "досвідчена", "впевнена", "працювала" — not "досвідчений", "впевнений", "працював"
  Italian female: "esperta", "motivata", "sono stata" — not "esperto", "motivato", "sono stato"
- If gender cannot be determined — default to masculine grammatical forms.

══════════════════════════════════════════
SALUTATION:
══════════════════════════════════════════
- English / default: "Dear Hiring Manager,"
- Italian: "Gentile Hiring Manager,"
- German: "Sehr geehrte Damen und Herren,"
- Ukrainian: "Шановний менеджер з найму,"
- NEVER write "[Hiring Manager Name]" or any bracket placeholder.

══════════════════════════════════════════
VOICE & TONE — THE MOST IMPORTANT SECTION:
══════════════════════════════════════════
The letter must sound like a real person wrote it. Not a template. Not a robot.

✅ WHAT THIS MEANS:
- Vary sentence length. Mix short punchy sentences with longer ones.
- Use natural transitions: "That's exactly why...", "What drew me to this role...", "Over the past three years...", "The reason I'm reaching out..."
- Show genuine curiosity about the company or role — reference something specific from the job description.
- Let the candidate's personality come through. Confident but not arrogant. Direct but not cold.
- One moment of genuine connection: a line that shows the candidate actually read the job description and thought about why they want THIS role at THIS company.

❌ WHAT TO AVOID:
- Robotic transitions: "Furthermore,", "In addition,", "Moreover,", "In conclusion,"
- Generic self-praise without evidence: "I am a highly motivated professional", "I am passionate about..."
- Starting every sentence with "I"
- Listing skills like a CV — instead, show skills through what you actually did

══════════════════════════════════════════
OPENING SENTENCE — CRITICAL:
══════════════════════════════════════════
The FIRST sentence after the salutation must immediately hook the reader. It should make them lean in.

✅ STRONG openings:
- Lead with a concrete result or number: "Eight team members, three languages, five years of on-time delivery — that's what I bring to this role."
- Direct match to their specific need: "You need someone who can manage multiple client projects without dropping a single deadline — that's been my daily reality for the past four years."
- A moment of genuine connection: "When I read your job description, one line stood out: [specific requirement]. That's been the core of my work at [company] for the past three years."
- Bold, specific statement: "Complex projects, demanding clients, tight deadlines — I don't just handle these situations, I've built systems to make them run smoothly."

❌ FORBIDDEN openings — NEVER use:
- "I am writing to apply..." / "I am the ideal candidate..." / "I am pleased to submit..."
- "With my proven experience..." / "Con la mia comprovata esperienza..." / "Mit meiner Erfahrung..."
- "З моїм досвідом..." / "Having [X] years of experience..."
- Any gerund as the very first word: "Managing...", "Successfully...", "Leveraging..."
- Any sentence starting with "I am" or "I have" as the first two words

══════════════════════════════════════════
CONTENT RULES:
══════════════════════════════════════════
- Mirror EXACT keywords from the Job Description naturally (ATS optimization).
- Use real metrics from the CV only. NEVER invent numbers or percentages.
- If no metrics exist — describe impact qualitatively and specifically.
- Do NOT invent degrees, companies, tools, or certifications not in the CV.
- Every claim must be grounded in the CV or job description.

FORBIDDEN SELF-ASSESSMENT PHRASES (all languages):
English: "I have significant experience", "results-driven", "team player", "dedicated professional", "I strongly believe", "I am highly skilled", "I am confident that I"
Ukrainian: "я маю значний досвід", "я є ідеальним кандидатом", "я глибоко впевнений", "результатоорієнтований", "я є відданим професіоналом"
Italian: "ho una significativa esperienza", "sono il candidato ideale", "professionista dedicato", "sono fortemente motivato"
German: "ich habe umfangreiche Erfahrung", "ich bin der ideale Kandidat", "ergebnisorientierter Profi", "ich bin hochmotiviert"

RULE: Replace any self-label with ONE concrete sentence about what you actually did.
BAD:  "I am experienced in team management"
GOOD: "Over three years, I coordinated a cross-functional team of 8 across two time zones to deliver 12 projects on schedule."

══════════════════════════════════════════
STRUCTURE:
══════════════════════════════════════════
- Salutation
- Opening paragraph: Strong hook + immediate connection to the role
- Body (1-2 paragraphs): 3-5 key JD requirements matched with real experience + specific achievements
- Closing: Genuine motivation for THIS company/role + clear call to action for interview
- NO sign-off, NO "Sincerely,", NO name — the template adds these automatically

══════════════════════════════════════════
LENGTH & FORMAT:
══════════════════════════════════════════
- Approximately ${wordLimit} words. Concise and punchy.
- Tone: ${tone || "Professional, Confident, and Direct"}.
- Plain text only. No markdown, no bullets, no headers, no asterisks.
- Blank line between paragraphs.
- No subject line, no meta-text, no explanations before or after the letter.

══════════════════════════════════════════
JOB DESCRIPTION:
══════════════════════════════════════════
${jobDescription.substring(0, 2000)}

══════════════════════════════════════════
CANDIDATE PROFILE:
══════════════════════════════════════════
${candidateProfile}
  `.trim();

  const contents = [promptText, ...(cvFilePart ? [cvFilePart] : [])];

  return await tryModel(async (modelId, temp) => {
    let text = await callGemini({
      modelId,
      temperature: temp,
      maxOutputTokens: 8192,
      contents,
    });

    text = text.replace(/^(Subject:|Oggetto:|RE:|Betreff:|Тема:).*?\n+/gmi, "").trim();
    text = text.replace(/```html|```/g, "");
    text = text.replace(/\n{0,2}(sincerely|best regards|kind regards|yours faithfully|cordiali saluti|met vriendelijke groet|mit freundlichen grüßen|з повагою|щиро ваш)[,.]?\s*\n[\w\s\-'.]+$/gi, "").trim();

    return text;
  });
};

export const parseCV = async (cvFilePart) => {
  const promptText = `Analyze this CV and extract details into valid JSON only.
Return ONLY raw JSON — no markdown, no backticks, no explanation.

{
  "fullName": "Name Surname",
  "email": "email@example.com",
  "phone": "+123...",
  "location": "City, Country",
  "linkedin": "url or empty string",
  "profession": "Current Job Title",
  "skills": ["skill1", "skill2", "skill3", "skill4", "skill5"],
  "experience": [
    {
      "title": "Job Title",
      "company": "Company Name",
      "duration": "Jan 2023 – Present",
      "achievements": ["Achievement with metric if available", "Achievement 2"]
    }
  ],
  "education": "Degree, University, Year",
  "languages": ["Language 1", "Language 2"],
  "certifications": ["Cert 1", "Cert 2"]
}`;

  return await tryModel(async (modelId) => {
    const text = await callGemini({
      modelId,
      temperature: 0.2,
      maxOutputTokens: 4000,
      contents: [promptText, cvFilePart],
      responseMimeType: "application/json",
    });

    const cleaned = text.replace(/^```json\s*/i, "").replace(/```\s*$/i, "").trim();
    return JSON.parse(cleaned);
  });
};

export const extractCompanyName = async (jobDescription) => {
  const promptText = `Extract the company name from this job description. Return ONLY the company name, nothing else. If you cannot find it, return "Unknown".

Job description:
${jobDescription.substring(0, 500)}`;

  return await tryModel(async (modelId) => {
    const text = await callGemini({
      modelId,
      temperature: 0.1,
      maxOutputTokens: 50,
      contents: [promptText],
    });
    return text.trim().replace(/["'.]/g, '') || "Unknown";
  });
};

export const generateLinkedInVersion = async (coverLetter, jobDescription, contactInfo) => {
  const promptText = `
You are an expert career coach. Write a SHORT LinkedIn Easy Apply message.
This goes in the "Cover Letter" field when applying via LinkedIn Easy Apply.

STRICT CONSTRAINTS:
1. Length: 150–200 words. No more, no less. Count carefully.
2. Tone: Confident, direct, human. No buzzwords or hollow phrases.
3. FORBIDDEN first words: "With my experience", "Con la mia esperienza", "I am writing",
   "I am the ideal", "Having X years", "I am pleased", "Successfully". NEVER start with these.
4. START with a strong hook: a concrete result, a number, or a direct match to their specific need.
5. Highlight 2–3 key strengths that directly match the job description.
6. End with a clear, natural call to action (e.g. "Happy to share more — looking forward to connecting.")
7. Output ONLY the message body. No subject line, no "Dear...", no explanations.
8. Do NOT copy any sentence directly from the Full Cover Letter — rephrase all achievements in a shorter, more conversational style.
9. Do NOT use any emoji or special symbols. Plain text only.
10. Write the COMPLETE message — never cut off mid-sentence. Finish properly.
11. Do NOT invent metrics or percentages not present in the cover letter or job description.

Candidate: ${contactInfo?.fullName || contactInfo?.name || "the candidate"}, ${contactInfo?.profession || ""}

Job Description:
${jobDescription.substring(0, 800)}

Full Cover Letter (context and achievements only — do NOT copy sentences):
${coverLetter.substring(0, 1200)}
  `.trim();

  return await tryModel(async (modelId) => {
    return await callGemini({
      modelId,
      temperature: 0.65,
      maxOutputTokens: 2048,
      contents: [promptText],
    });
  });
};

export const generateSuggestions = async (coverLetter, jobDescription) => {
  const promptText = `
You are a senior career coach reviewing a cover letter.

Analyze the cover letter against the job description and give exactly 3 short, specific, actionable suggestions to strengthen the application.

RULES:
- Each suggestion must be max 20 words.
- Be specific: reference actual skills, tools, or phrases from the job description.
- Focus on what is MISSING or WEAK — not what is already good.
- Do NOT rewrite the letter, only advise what to change or add.
- Do NOT number the suggestions, do NOT use bullet symbols.

OUTPUT FORMAT — exactly 3 lines, each on its own line, no prefix, no numbering:
Suggestion one here
Suggestion two here
Suggestion three here

Job Description:
${jobDescription.substring(0, 1000)}

Cover Letter:
${coverLetter.substring(0, 1200)}
  `.trim();

  return await tryModel(async (modelId) => {
    return await callGemini({
      modelId,
      temperature: 0.4,
      maxOutputTokens: 1024,
      contents: [promptText],
    });
  });
};

export const analyzeATSScore = async (coverLetter, jobDescription) => {
  const promptText = `
You are an ATS (Applicant Tracking System) expert. Analyze how well the cover letter matches the job description.

Return ONLY valid JSON, no markdown, no explanation:
{
  "score": <integer 0-100>,
  "matched": ["keyword1", "keyword2", "keyword3"],
  "missing": ["keyword1", "keyword2", "keyword3"],
  "tip": "<one short actionable tip under 15 words>"
}

Rules:
- score: 0-100 integer. Above 75 is good, 50-74 is fair, below 50 is weak.
- matched: up to 6 important keywords/phrases from JD that appear in the letter
- missing: up to 5 important keywords/phrases from JD NOT present in the letter
- tip: specific, actionable, max 15 words

Job Description:
${jobDescription.substring(0, 1200)}

Cover Letter:
${coverLetter.substring(0, 1200)}
  `.trim();

  return await tryModel(async (modelId) => {
    const text = await callGemini({
      modelId,
      temperature: 0.2,
      maxOutputTokens: 512,
      contents: [promptText],
      responseMimeType: "application/json",
    });
    const cleaned = text.replace(/^```json\s*/i, "").replace(/```\s*$/i, "").trim();
    return JSON.parse(cleaned);
  });
};

export const generateInterviewQA = async (coverLetter, jobDescription, contactInfo) => {
  const promptText = `
You are a senior hiring manager and interview coach.

Based on the job description and candidate's cover letter, generate exactly 8 likely interview questions and ideal short answers.

Return ONLY valid JSON, no markdown:
[
  { "q": "Question text?", "a": "Ideal answer in 2-3 sentences." },
  ...
]

Rules:
- Mix behavioral (Tell me about a time...), situational, and role-specific questions
- Answers should reference the candidate's background from the cover letter
- Keep answers concise: 2-3 sentences each
- Make questions realistic and specific to the role

Candidate name: ${contactInfo?.fullName || "the candidate"}

Job Description:
${jobDescription.substring(0, 1200)}

Cover Letter:
${coverLetter.substring(0, 1000)}
  `.trim();

  return await tryModel(async (modelId) => {
    const text = await callGemini({
      modelId,
      temperature: 0.6,
      maxOutputTokens: 3000,
      contents: [promptText],
      responseMimeType: "application/json",
    });
    const cleaned = text.replace(/^```json\s*/i, "").replace(/```\s*$/i, "").trim();
    return JSON.parse(cleaned);
  });
};

export const generateSubjectLines = async (coverLetter, jobDescription, contactInfo) => {
  const promptText = `
You are an expert at writing compelling email subject lines for job applications.

Generate exactly 3 subject line options: one formal, one direct/bold, one creative.

Return ONLY valid JSON, no markdown:
[
  { "style": "Formal",   "subject": "Application for [Role] — [Name]" },
  { "style": "Direct",   "subject": "..." },
  { "style": "Creative", "subject": "..." }
]

Rules:
- Each under 60 characters
- No generic "I am applying for..." phrasing
- Reference the actual role from the job description
- Use the candidate's name where appropriate
- Make each distinctly different in style

Candidate: ${contactInfo?.fullName || "the candidate"}
Job Description: ${jobDescription.substring(0, 600)}
Cover Letter snippet: ${coverLetter.substring(0, 400)}
  `.trim();

  return await tryModel(async (modelId) => {
    const text = await callGemini({
      modelId,
      temperature: 0.7,
      maxOutputTokens: 512,
      contents: [promptText],
      responseMimeType: "application/json",
    });
    const cleaned = text.replace(/^```json\s*/i, "").replace(/```\s*$/i, "").trim();
    return JSON.parse(cleaned);
  });
};

export const generateFollowUp = async (originalLetter, jobDescription, contactInfo, daysSince) => {
  const promptText = `
You are an expert career coach. Write a SHORT, professional follow-up email for a job application.

CONTEXT:
- The candidate applied ${daysSince} days ago and has not heard back.
- This is a polite follow-up — NOT a desperate plea. Confident and brief.

STRICT RULES:
1. Length: 80–120 words MAX. Short and respectful of the reader's time.
2. Tone: Warm, professional, confident. NOT pushy or apologetic.
3. Structure:
   - Line 1: Brief reminder of who they are and which role they applied for
   - Line 2–3: One specific detail from the original letter that reinforces their fit (do NOT copy — rephrase naturally)
   - Final line: Simple ask — still interested, happy to provide anything else, looking forward to next steps
4. NO subject line. Output ONLY the email body.
5. NO "I am following up on my application" as the opener — too generic.
6. Start with something like: "I wanted to briefly follow up on my application for [role]..." or reference a specific detail.
7. End with a natural sign-off like "Best regards," followed by the candidate's name.
8. Plain text only. No markdown, no bullets.

Candidate: ${contactInfo?.fullName || "the candidate"}
Role applied for: extracted from job description below
Days since application: ${daysSince}

Job Description (for context):
${jobDescription.substring(0, 600)}

Original Cover Letter (use for context — do NOT copy sentences directly):
${originalLetter.substring(0, 800)}
  `.trim();

  return await tryModel(async (modelId) => {
    return await callGemini({
      modelId,
      temperature: 0.6,
      maxOutputTokens: 512,
      contents: [promptText],
    });
  });
};